INSERT INTO TODOS VALUES (TRUE, default, '✏️ SpringBoot 공부하기');
INSERT INTO TODOS VALUES (FALSE, default, '🛍️ 장보기');
INSERT INTO TODOS VALUES (FALSE, default, '📕 독서하기');
INSERT INTO TODOS VALUES (FALSE, default, '💧 물 2L 마시기');
INSERT INTO TODOS VALUES (FALSE, default, '🚶🏻 산책 30분');
INSERT INTO TODOS VALUES (FALSE, default, '💪🏻 헬스 1시간');
INSERT INTO TODOS VALUES (TRUE, default, '📜 알고리즘 공부하기');
INSERT INTO TODOS VALUES (FALSE, default, '🧹 방청소하기');
INSERT INTO TODOS VALUES (FALSE, default, '🧽 설거지하기');
INSERT INTO TODOS VALUES (FALSE, default, '🫶🏻 구경 와주셔서 감사합니다 🫶🏻');